### ISSUE TITLE
Needs to be updated as some OS aren't available.

### ISSUE THREAD

**Issue by rgleason** [nohal/launcher_pi#11]
Some reports that Launcher is missing after updating O.

**Comment by nohal** [comment]
Which OS is not supported exactly? I do not see any gaps in https://docs.google.com/spreadsheets/u/1/d/1_xQJ4gIGIp0rlexZTMdIkxrLMKKYzKQ7UzbCkGQ_IG4/htmlview

**Comment by rgleason** [comment]
Ok, sorry, I don't know. They were not specific, it was on CF.  Closing.
