### ISSUE TITLE
Screen Resolution and Text & other Scale problems

### ISSUE THREAD

**Issue by rgleason** [nohal/launcher_pi#2]
Cannot get access to Edit Menu Command.
Would like both Preference menus to be adjustible and settings saved.
Would like Toolbar menu to be adjustible and settings saved.

http://www.cruisersforum.com/forums/f134/launcher-plugin-119149.html#post2083048

**Comment by rgleason** [comment]
Cannot grab corner and drag it bigger. The edit area should open big enough to enter the command.
![screenshot 53](https://cloud.githubusercontent.com/assets/2363959/23384863/a4ff5cae-fd1a-11e6-8cd0-244c971b79fe.png)

**Comment by rgleason** [comment]
Pavel,
In debug mode MS VStudio where would I look to get the stretch function to work on the Menu to be able to expose the Command field, so I can enter a command.

Is there some particular file or line I should look at and adjust?  Or is this one of those wxforms isssues?
Thanks.

**Comment by rgleason** [comment]
This is NOT fixed, so why close it?
![screenshot 298](https://user-images.githubusercontent.com/2363959/39089102-5985ad7a-458d-11e8-9b68-b1c3f92f7e5d.png)

**Comment by nohal** [comment]
Use the damn reopen button

**Comment by rgleason** [comment]
Ok, found it at the top. I will try to use wxFormbuilder to make it sizeable, unless you don't trust me.

**Comment by rgleason** [comment]
PS thanks for v4.8.8

**Comment by nohal** [comment]
What do you talk about now, please?

**Comment by nohal** [comment]
And while at it, please tell me which of the windows this plugin creates is still not resizable with the current code. All are for me.

**Comment by rgleason** [comment]
I had just downloaded and tested using the Download page 1.1 version.    I will git fetch and compile tomorrow morning. Thanks.

**Comment by nohal** [comment]
Before you start to panic next time, please take those 5 seconds to realize you are downloading something that is 2 years and 2 months old, please.
