### ISSUE TITLE
Unkown image data format

### ISSUE THREAD

**Issue by pavelpasha** [nohal/launcher_pi#3]
When i launch the OpenCPN, plugin give me the error: "Unkown image data format".

**Comment by nohal** [comment]
Sorry, I don't have a clue what you talk about. To start:
OpenCPN version?
Plugin version?
Operating system?
HW Architecture?
Your OpenCPN logfile?
Screenshot of "The plugin giving you the error"?

**Comment by pavelpasha** [comment]
OpenCPN version is 4.4.0
Plugin version - master 
OS - WIN10
wxWidget version 3.10
Compiled via VS2015 compiler (Sorry for my English)
![111](https://cloud.githubusercontent.com/assets/13303084/23092421/533b1ea8-f5db-11e6-970a-1b9842f5022f.png)

**Comment by nohal** [comment]
Harmless wxWidgets assert. Simply hit Cancel.

**Comment by pavelpasha** [comment]
I don`t think so, because the OpenCPN stop working(not responding) when i hit Cancel.

**Comment by nohal** [comment]
Well, you are using an unsupported compiler and unsupported version of wxWidgets. What do you expect me to do about it? If the assert bothers you and causes you problems, fix it and send me a pull request.

**Comment by pavelpasha** [comment]
I have the same error with a wxWidget 3.0.2. I think that it`s my fault. Maybe i did something wrong. Lets see:

1)Clone the repository
2)Create build dir and build project with cmake to it
3)Drop an opencpn.lib into build directory
4)Open the .sln project and compile it with no errors
5)Copy the compiled launcher_pi.dll  to plugins directory
6)Create launcher_pi dir in plugins catalogue and copy to it data dir with .svg files inside
Is it wrong?

**Comment by nohal** [comment]
What exactly is it you are trying to do? As far as I know these are debug mode asserts, so you seem to be trying to "develop" something, but in that case it makes absolutely no sense not to build the plugin inside the main OpenCPN tree and not having to copy anything anywhere.

**Comment by pavelpasha** [comment]
My final goal is to develop a plugin for docking pilot which will draw very detailed real scale vectior ship (more then 5 points,  in order to even draw the shape of the nose and stern of the vessel ). But i dont even found the API documentation and dont know what API calls will helps me to change standart ship marker.
I need an detailed pludig development manual for beginners, but i cant find.
So i decided to start with the fact that at least build and compile plugin with no errors, then based on it to try to do something. Unfortunately, none of the available plug-ins do not work for me. Most of them gives the same error. Even the openCPN gives me `Error	LNK2005	_XML_ParserCreate already defined in wxexpatd.lib(xmlparse.obj)	opencpn	C:\Users\virtualBox\Desktop\OpenCPN-4.4.0\build\expat.lib(expat.dll)`  at the end of compilation.

**Comment by rgleason** [comment]
> What exactly is it you are trying to do? As far as I know these are debug mode asserts, so you seem to be trying to "develop" something, but in that case it makes absolutely no sense not to build the plugin inside the main OpenCPN tree and not having to copy anything anywhere.

Agreed, but I have been Debugging Plugins inline with OpenCPN and have been getting these "harmless" Asserts which crash OpenCPN in different situations listed below, when I go to Options > Plugins  then Crash.
1. Running MS VStudio 2013 in debug mode (after cmake -T v120_xp .. and build) with various none internal plugins configured see the not complete list here  at the bottom https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_plugins_to_debug

2. When I have copied necessary files to source\build\release to duplicate the NSIS directory and I first run Opencpn /p  portable to create opencpn.ini. Then I go to Options>Plugins and all the plugins are there just fine.  Then shouldn't I be able to use just OpenCPN the next time which uses the opencpn.ini in ProgramData\opencpn\   and then go to Options>Plugins  and voila!! CRASH.

Why?

**Comment by rgleason** [comment]
Also see this please: http://www.cruisersforum.com/forums/f134/beta-test-technical-30929.html

**Comment by rgleason** [comment]
PS I am using MS SurfPro3  Win10 MS Visual STudio 2013 and wxWidgets 3.0.2  Opencpn v4.5.221 all standard stuff.
Yes, maybe I have something wrong, like not copy I necessary file, but I have gone through this file by file and have tried to improve TDan's batch file and  that can all be found on the this page and Paragraph
[https://opencpn.org/wiki/dokuwiki  /doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows#setup_batch_files1](url)   
6.1 Setup Batch Files

This batch file shows what I have copied to the source\build\release directory.  I am hoping others will also check this batch files like TDan, Hakan and Mike.   ...and perhaps you?  

Also I tried to make this dokuwiki page a little easier for newbie users so they can understand what is supposed to happen with each step.

Thanks.

**Comment by pavelpasha** [comment]
I installed completly clear OS, tnen installed the VS2013 and wxWidget 3.0.2 and still have the "Unkown image data format" message. Its looks like the plugin cant find the path to data/.svg - files for some reason.

**Comment by nohal** [comment]
Copy the SVGs where they have to be. If you are running under debug and not installing the plugin, it of course does not find the files. Or implement something brilliant to figure out where your source tree is and look for the data files in it and send me a patch.

**Comment by rgleason** [comment]
pavelpasha,  look at this page for list of plugins that should comiple in debug mode.
Certainly the 4 internal plugins  chartdldr, dashboard, wmm, grib!!

Also have you copied the data directory to the right location?  See this page writeup.
((https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows:compiling_plugins_to_debug))

Have you copied the debug name_pi.dll to the right location?

**Comment by pavelpasha** [comment]
rgleason, of corse i copied. Copied manualy and  builded install package and installed it.

**Comment by rgleason** [comment]
Ok. Out of curiosity, did you follow this page, which we are trying to improve?
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows

And did you use the batch files?  (probably not...)
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:compiling_windows#setup_batch_files1

Are there any specific suggestions for improvement?

**Comment by rgleason** [comment]
I wonder if you need to add  wxWidgets  "aui"  in the cmake file.   I will try to do this myself now.

**Comment by nohal** [comment]
What for and why?

**Comment by rgleason** [comment]
Pavel, to help pavelpasha get it working.
but I just git fetched  and there were new files, It works fine for me. No changes needed.

I like the README   ##Variable substitution    nice.

**Comment by rgleason** [comment]
When I installed it and enabled it the plugin crashed opencpn.
I have these in source\buildwin
```
  libcurl.dll
  libcurl.lib  
  NSIS.template.in
  ocpn_gltest1.exe
  zlib1.dll
  <DIR>          crashrpt 
  <DIR>          expat-2.1.0
  <DIR>          gtk
  <DIR>          vc
  <DIR>          wxWidgets
```
  
I wonder what I am missing.
I am going to delete and git clone

**Comment by rgleason** [comment]
git clone ...
for a Standalone Plugin compile.
Unpacked  OpenCPN Buildwin.7z and put it in buildwin
In  README No other files required.
Copied  v4.2 opencpn.lib to build
then ran
cmake -T v120_xp ..
cmake --build . --config release
cmake --build . 
cpack
Completed no errors.
Installed the NSIS package.

I checked that the data files were copied to the NSIS directory.
Yes they were along with svg files   and another Share directory.
C:\Users\..\n-launcher_pi\build\_CPack_Packages\win32\NSIS\launcher_pi-1.1-win32\plugins\launcher_pi\data

Loaded opencpn and turned on launcher. 
**_Opencpn bombed._**
Do I need a more recent opencpn.lib?     -- No there were no complaints.

**Comment by pavelpasha** [comment]
@rgleason , I reinstalled and recompiled wxWidgets 3.0.2 from Developer Command Prompt for VS2013 with keys - "nmake -f makefile.vc BUILD=release SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_" and "nmake -f makefile.vc BUILD=debug SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_" and the error has gone! It works now!  Every little thing matters!

**Comment by rgleason** [comment]
Interesting. I need to install SDK71_ on a Win10 machine now. I wonder if some file changed...norton?
On another machine, same setup, compile earlier Launcher_pi  1.0 and it compiled standalone and it worked. None of the svg dll's were required in source\buildwin.  

> C:\Users\..\GitHub\o-plugin\n-launcher_pi>git branch -va
> * master                1525509 Update the build/packaging system
>   remotes/origin/HEAD   -> origin/master
>   remotes/origin/master 1525509 Update the build/packaging system
> 
Will try 1.1 now on that machine... git fetch

**Comment by rgleason** [comment]
On the other machine, git fetched 1.1 and compiled without adding Svg dll's to buildwin, just to learn what happens. It compiled successfully with no errors, and I could complete the NSIS install. Opening Ov4.4 no plugins loaded after launcher. Launcher was not loaded.  --Should/can there be a cmake message that Svg buildwin files were not found during cmake -T ..?

Then I compiled Launcher with the Svg files copied to source\buildwin.. it completed successfully and NSIS install package was made. Executed the NSIS install to  Opencpn4.4. Ran Opencpn4.4 and Launcher was in the Toolbar and when I clicked, the two entries for TDan VDRplayer were there.  I expect Laucher runs properly, because the VDRplayer prompts appeared properly, but for some reason the Hartmut & Hakan nmea files did not show in the nmea popup.  I'll trace this out later.  The point is that launcher compiles fine on this machine.

Perhaps some wxWidget is missing or corrupted on the other machine.  Anyway Launcher 1.1 compiles and works.

**Comment by rgleason** [comment]
>  I expect Laucher runs properly, because the VDRplayer prompts appeared properly, but for some reason the Hartmut & Hakan nmea files did not show in the nmea popup. I'll trace this out later. 

Launcher was setup with two commands that run TDan VDRplayer for testing purposes. For some reason my data connection was set on TCP when UDP was needed.

Title: Hartmut-Netherlands
Command: c:\python27\python c:\python27\VDRServer1.py C:\Data-Dart\Nmea\Hartmut-Netherlands.txt 127.0.0.1 2947 .033

Title: Haken-Sweden
Command: c:\python27\python c:\python27\VDRServer1.py C:\Data-Dart\Nmea\Hakefjord-Sweden.txt 127.0.0.1 2947 .033

Type:Net Dataport:127.0.0.1 2947 .033  Parameters:UDP  Connection:In/out  Filters: none

**Comment by rgleason** [comment]
This can be closed now.  --It is.
