### ISSUE TITLE
Close Window

### ISSUE THREAD

**Issue by RooieDirk** [nohal/launcher_pi#5]
Ha works great! 
For convenience would it be possible to have the option 'close window on action' select per option?
For say a KBD:!F6,F6 it would be good to not close the window, where a KBD:!F11,F11 a closing would be just fine.
Or maybe a close timer? Auto close the window after .. seconds.

**Comment by aviatorhh** [comment]
This feature has been implemented and is nice.
Unfortunately after restarting OpenCPN 5.8.2 ist does not work again. The checkbox is enabled in the settings. Only after deselecting and reselecting it works again.
